"""modift blog_info

Revision ID: 19ba48789e10
Revises: 
Create Date: 2019-09-29 23:47:34.217427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19ba48789e10'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_categories_name', table_name='categories')
    op.drop_table('categories')
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_column('articles', 'category')
    op.add_column('blogInfo', sa.Column('self_intro', sa.String(length=64), nullable=True))
    op.drop_column('blogInfo', 'navbar')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogInfo', sa.Column('navbar', sa.VARCHAR(length=64), nullable=True))
    op.drop_column('blogInfo', 'self_intro')
    op.add_column('articles', sa.Column('category', sa.VARCHAR(length=32), nullable=True))
    op.create_foreign_key(None, 'articles', 'categories', ['category'], ['name'])
    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('ix_categories_name', 'categories', ['name'], unique=1)
    # ### end Alembic commands ###
